#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<mpi.h>
#define send_data_tag 2001
#define return_data_tag 2002

void buildTree(int start,int end,int*,int,int,int);

void printInorder(int id,int* arr,int start,int end) {
   if(start > end) {
      return; 
   }
   printInorder(id,arr, start*2 + 1, end); 
   printf("%d\t", arr[start]); 
   printInorder(id,arr, start*2 + 2, end);
   
}

int main(int argc, char *argv[]) {
   int i,N=512,id,p;
   int tree[N],*FinalTree=NULL;
   int turns;
   double start,finish;
   MPI_Init(&argc, &argv);
   MPI_Comm_rank(MPI_COMM_WORLD, &id);
   MPI_Comm_size(MPI_COMM_WORLD, &p);
   if(id==0) {
      start = MPI_Wtime();
      printf("Inorder Tree -\n");
   }
   for(turns=id;turns<p;turns+=p) {
      int offset=turns*N;
      buildTree(0,N,tree,0,offset,N);
      printf("Process %d - ",id);
      printInorder(id,tree,0,N-1);
      printf("\n");
      
   }
   FinalTree=(int*)malloc(N*p*sizeof(int));
   MPI_Gather(&tree,N,MPI_INT,FinalTree,N,MPI_INT,0,MPI_COMM_WORLD);
   if(id==0) {
      printf("\nChild Tree Generated by processes in array form -");
      for(i=0;i<N*p;i++) {
         if(i%N==0) {
            printf("\nProcess %d - ",i/N);
         }
         printf("%d\t",FinalTree[i]);
      }
      finish = MPI_Wtime();
      printf("\nExecution time = %f seconds\n",(finish-start));
   }
   MPI_Finalize();
   return 0;
}

void buildTree(int start,int end,int* tree,int k,int offset,int N) {
   if(start<=end && k<=N-1) {	
      int mid = (end+start+1)/2;
      tree[k] = mid+offset;
      buildTree(start,mid-1,tree, k*2+1,offset,N);
      buildTree(mid+1,end,tree,k*2+2,offset,N);
   }
}
